require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  - rubocop-rubycw

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/TrailingEmptyLines:
  EnforcedStyle: final_blank_line

